spring:
  config:
    activate:
      on-profile:
        - dev
  data:
    mongodb:
      host: ${HOST_MONGO:localhost}
      port: ${PORT_MONGO:27017}
      database: ${DATABASE_MONGO:email}
  mail:
    host: ${HOST_MAIL:smtp.gmail.com}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT:465}
    properties:
      mail:
        smtp:
          ssl:
            enable: ${MAIL_SSL_ENABLE:true}