spring:
  config:
    activate:
      on-profile:
        - prod
  mail:
    host: ${HOST_MAIL:smtp.gmail.com}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT:465}
    properties:
      mail:
        smtp:
          ssl:
            enable: ${MAIL_SSL_ENABLE:true}